# Forbidden to change
[stable]
bug_report_md = ".github/ISSUE_TEMPLATE/bug_report.md"
feature_request_md = ".github/ISSUE_TEMPLATE/feature_request.md"
test_yaml = ".github/workflows/test.yml"
dependabot_yml = ".github/dependabot.yml"

# Dynamic configuration
[dynamic]
