[template]
version = "1.0.0"

[stable]
bug_report_md = ".github/ISSUE_TEMPLATE/bug_report.md"
feature_request_md = ".github/ISSUE_TEMPLATE/feature_request.md"
test_yaml = ".github/workflows/test.yml"
dependabot_yml = ".github/dependabot.yml"
rustfmt_toml = "rustfmt.toml"
tsconfig_json = "tsconfig.json"

# Dynamic configuration
[dynamic]

[scripts]
format = "cargo fmt"
lint = "cargo clippy"
build = "cargo build"
test = "cargo test"
test_coverage = "cargo tarpaulin --fail-under 95 --exclude-files 'src/main.rs'"
